Legger til config for prod-sbs
navikt/dittnav-event-test-producer pull request #45
Opened 2021-02-17 14:10 UTC by Robert-Larsen

Absolutt minimumsversjon. Litt fristende å gå for denne, da vi kun lar endepunktet som produserer ett og ett beskjed-event være tilgjengelig. Dette er beskyttet med et bruker-token fra før. Hva tenker dere? Noe jeg ikke tenker på?

Se også PR for brukernotifikasjon-topic-iac

2021-02-17 14:23 UTC, chris-santa approved these changes

2021-02-17 17:19 UTC, greger-nl approved these changes

2021-02-17 17:22 UTC, greger-nl requested changes
Her må vi vel egentlig legge til en `nav.no` for at en innlogget bruker skal kunne nå endepunktet.

2021-02-17 17:57 UTC, Robert-Larsen commented
> Her må vi vel egentlig legge til en `nav.no` for at en innlogget bruker skal kunne nå endepunktet.

Ja, vi må vel kanskje det? Jeg tenkte egentlig bare nais.oera fra utviklerimage, men hvis Tone bl.a. skal teste så trengs vel nav.no-ingress. Og det må vel kanskje også være der for at tokenet skal flyte riktig.

2021-02-18 05:52 UTC, greger-nl approved these changes

2021-02-18 05:57 UTC, greger-nl commented
> > Her må vi vel egentlig legge til en `nav.no` for at en innlogget bruker skal kunne nå endepunktet.
> 
> Ja, vi må vel kanskje det? Jeg tenkte egentlig bare nais.oera fra utviklerimage, men hvis Tone bl.a. skal teste så trengs vel nav.no-ingress. Og det må vel kanskje også være der for at tokenet skal flyte riktig.

Enig. Jeg legger til et GET-endepunkt, som ikke tar noen input, for å lage test-eventet.

2021-02-18 08:03 UTC, merged